### ISSUE TITLE
minSdkVersion 19

### ISSUE THREAD

**Issue by AngleV** [lawloretienne/DiscreteSlider#1]
is it possible to change it to minSdkVersion 15 ?

**Comment by lawloretienne** [comment]
Sure, I haven't tested that yet.  Let me do that first.

**Comment by lawloretienne** [comment]
I just changed the minSdkVersion down to 14.  I pushed the changes to  Sonatype.  This should go live in a couple of hours.  It will be in version 0.0.4 of the library.
