### ISSUE TITLE
No able to update slider tickMarkCount in runtime

### ISSUE THREAD

**Issue by hatak30** [lawloretienne/DiscreteSlider#10]
Hi 

I'm trying to have dynamic number of tickMarkCount, however after change in that value, its not reflected in UI

so when original y slider has 4 positions and in run-time I'm incising it it 5 then, slider moves like there are 5 positions but in UI I still se only four, is there any way to resolve it?

**Comment by lawloretienne** [comment]
This is now fixed in version 0.0.8 which will be live in a few hours.
