### ISSUE TITLE
Backdrop Fill Color Not Working

### ISSUE THREAD

**Issue by StuStirling** [lawloretienne/DiscreteSlider#11]
Hi,

Trying to set the`backdropFillColor` both in XML and programatically, however it is not changing. It always stays the color that's in the demo, grey.

I want it to match the color of a layout in it's background so ideally I'd set the background to transparent but failing that, I would set it to a color of my choosing programatically.

Is this a bug?

**Comment by lawloretienne** [comment]
which version of the library are you using?

**Comment by lawloretienne** [comment]
Re-open this if its still an issue.  I am closing this as i cannot duplicate the issue.

**Comment by StuStirling** [comment]
Hi sorry, for not feeding back earlier. I managed to get it working. Unfortunately it doesn't work perfectly because the circles representing options are different views to the underlying bar hence as they are overlayed you get different opacities. Perhaps if I get change I will create a fork to make it one view?

**Comment by lawloretienne** [comment]
Yep. Since they are different shapes it really just works with color with no opacity. I'm curious to see what your fork looks like.
