### ISSUE TITLE
how to set position ? 

### ISSUE THREAD

**Issue by ravivghl** [lawloretienne/DiscreteSlider#12]
i want to give position pogramatically.
 like set position with number . `slider.setPosition(1)`

**Comment by lawloretienne** [comment]
Yes you can do that
https://github.com/lawloretienne/DiscreteSlider/blob/47ebef985474e158640347097c4f464c63688d0f/library/src/main/java/com/etiennelawlor/discreteslider/library/ui/DiscreteSlider.java#L125
