### ISSUE TITLE
Can not build from CLI

### ISSUE THREAD

**Issue by vbauer** [lawloretienne/DiscreteSlider#2]
It looks like gradle-wrapper.jar file was missed in this repository.

**Comment by lawloretienne** [comment]
What is CLI?  I can see the gradle-wrapper.jar file on my local machine but for some reason it is not checked into the repo.  I can't quite figure out which statement in my .gitignore is preventing that file from being checked in.

**Comment by vbauer** [comment]
CLI - command line interface (in my case it is `bash`). I think the root of this problem is this line `*.jar`. You can fix it using the following rule: `!gradle-wrapper.jar`.

```
An optional prefix ! which negates the pattern; any matching file excluded by a previous pattern will become included again. If a negated pattern matches, this will override lower precedence patterns sources.
```

**Comment by lawloretienne** [comment]
Sweet.  Okay i just updated .gitignore and that .jar file is now checked into the repo.  Let me know if you still have issues.

**Comment by vbauer** [comment]
👍
