### ISSUE TITLE
How can i change thumb icon drag time until to other position?

### ISSUE THREAD

**Issue by ravivghl** [lawloretienne/DiscreteSlider#3]
I want to change thumb icon when i drag my icon to other position. i could not found proper solution from this library.

**Comment by lawloretienne** [comment]
The
DiscreteSlider.OnDiscreteSliderChangeListener interface has a method
public void onPositionChanged(int position) {} .
You could update the thumb here.

**Comment by lawloretienne** [comment]
The
DiscreteSlider.OnDiscreteSliderChangeListener interface has a method
public void onPositionChanged(int position) {} .
You could update the thumb here by calling DiscreteSlider.setThumb(thumbDrawable);

**Comment by lawloretienne** [comment]
Does that work for you @ravivghl ?

**Comment by lawloretienne** [comment]
Im closing this now.  Reopen if you still have issues.

**Comment by ravivghl** [comment]
@lawloretienne  please check my issue
