### ISSUE TITLE
How to change Thumb Icon when i select and drag to other position?

### ISSUE THREAD

**Issue by ravivghl** [lawloretienne/DiscreteSlider#4]
I want to change icon of thub when i select and drag to other position but not found any mehod for that.
discreteSlider.setOnDiscreteSliderChangeListener in i can set thumb at position but select and drag time change icon. As like Uber app in select time change thumb icon.

**Comment by lawloretienne** [comment]
You may want to fork my library.  If you take a look at the DiscreteSeekBar.java class there is a Seekbar.OnSeekBarChangeListener.  That listener has 3 methods to override : `onStartTrackingTouch()` `onProgressChanged()` and `onStopTrackingTouch()`.  Maybe in `onProgressChanged()` you may want to put some of this logic to notify a separate interface that will be able to get the actual position so then you can update the thumb drawable.
