### ISSUE TITLE
Set progress 

### ISSUE THREAD

**Issue by mgursch** [lawloretienne/DiscreteSlider#5]
hello

how can I set the current progress. Need something like

slider.setCurrentProgress(4);

Thanks a lot

**Comment by ghost** [comment]
Same here, I'm wondering if that's possible.

Can you let us know please.

Thanks.

**Comment by lawloretienne** [comment]
So do you want something like ... If there are 10 tickmarks and you say setCurrentTickmark(4) it will set the slider to the 5th tickmark since it would be 0 offset?  I don't want to call it progress since this is not really a progress bar.

**Comment by ghost** [comment]
Yes, I believe that's what we both meant to say.

**Comment by mgursch** [comment]
yes thats it, exactly.

you use such a control to set a specific value. if you have an edit option you have to preselect the value. so you need a setCurrentTickmark(int x) method

thanks a lot

**Comment by mgursch** [comment]
Is there any progress on this ??

**Comment by lawloretienne** [comment]
So I want to create a custom attribute but what should it be called 
`DiscreteSlider_progress`
or
`DiscreteSlider_position`
or
`DiscreteSlider_tickMark` .

I kind of prefer `DiscreteSlider_position` .

How would you expect it to handle when a developer sets a position that is out of bounds? For example if there are 5 tickmarks with positions 0,1,2,3,4 then if a developer sets the position to -1 or 6 what should happen?

**Comment by mgursch** [comment]
the naming is up to you. personally would prefere "position";

please add a method to set the "position" by code.

if the "position" is out of bounds 
1) throw an outofboundsexception
2) just set to MAX or MIN

better would be 2)

thanks a lot

**Comment by sgaikar1** [comment]
hii @lawloretienne  i also have this same issue... you can check minimum position and maximum positions of slider before setting them programmatically... 
Lets say u want to set minimum value -1 and max value 6 then
you just need to call getMin and getMax before setting new position to handle outofbounds issue.. after getting min and max you can check if -1 <min then min = -1 
and 6>max then set max = 6; so you can elemenate such problem of out of bound exception.

Please update your library with this issue.. and i will try to contribute in this library in future becouse you did an awesome work in this 👍

**Comment by lawloretienne** [comment]
Now you can set the position in xml or in java.

Here is how you would do it in xml :
`app:position="1"`

Here is how you would do it dynamically :
`discreteSlider.setPosition(1);`

I have updated the sample so you can see how it is done.  Also I am accounting for out of bounds values and just set to either MIN or MAX.

I just pushed this so it should be live in a couple of hours.  You will need to start using version 0.0.7 to get these changes.

**Comment by sgaikar1** [comment]
Thanx i will check it

**Comment by sgaikar1** [comment]
working as i wanted 👍

**Comment by mgursch** [comment]
thanks a lot :)
