### ISSUE TITLE
How to change speed of slider

### ISSUE THREAD

**Issue by sgaikar1** [lawloretienne/DiscreteSlider#6]
Please guide me to change the smooth scroll speed of slider.

**Comment by lawloretienne** [comment]
Are you referring to when you click a tickmark instead of dragging the thumb of the slider? do you want it to go faster or slower?

**Comment by sgaikar1** [comment]
in both situations it needs to change speed of slider.. also sometimes thumb is not detecting touch event.. i guess touch area of thumb is very small, so to slide thumb we need to give efforts of touching it properly in center..

**Comment by lawloretienne** [comment]
you can instead use a larger thumb drawable and it will make it easier to drag

**Comment by lawloretienne** [comment]
you may want to fork this library to change the speed of how the thumb transitions

**Comment by sgaikar1** [comment]
okay i will give a try on your suggession :)

**Comment by sgaikar1** [comment]
and yes will fork this library in somedays.. right now i dont have much time to focus on other developments
